<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIxtWZr3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIxtWZr3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIxtWZr3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIxtWZr3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerIxtWZr3\App_KernelDevDebugContainer([
    'container.build_hash' => 'IxtWZr3',
    'container.build_id' => '4d161e3e',
    'container.build_time' => 1659996934,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIxtWZr3');
