<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_weather' => [[], ['_controller' => 'App\\Controller\\WeatherController::index'], [], [['text', '/weatherAdd']], [], [], []],
    'app_add_weather_forecast' => [[], ['_controller' => 'App\\Controller\\WeatherController::addRecord'], [], [['text', '/']], [], [], []],
    'app_weather_forecasts' => [[], ['_controller' => 'App\\Controller\\WeatherController::weatherForecasts'], ['page' => '\\d+'], [['text', '/weatherForecasts']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
